### ISSUE TITLE
change json format

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-android#165]
Hey @PhoenixWright should I go for a /v2/ approach on the server (that would be a TON of work) or.. I have no idea :)

**Comment by PhoenixWright** [comment]
So you’re basically changing the format of what you’re returning? What exactly is the change? If it’s only new values you don’t need to do a v2.

If it’s a bigger refactor you can also pass in a parameter from the client saying which version you’re asking for rather than have a second /v2 path. AWS actually does this by having the client pass in a date that represents a version of the API.

Plenty of options. Depends on the change.

**Comment by FultonBrowne** [comment]
@PhoenixWright  I am adding one new value but all other versions of the app are decoding directly from the old class using GSON. I was thinking about using params and will most likely do that if all else fails

**Comment by PhoenixWright** [comment]
GSON can ignore fields somehow, maybe by default. You should test if it breaks for you locally if you add the new one, because you always want to just ignore new fields in the client if you’re not already. You can at least make sure you configure GSON the way you want for all future versions of the app and do whatever you need to do this time.

**Comment by FultonBrowne** [comment]
Thanks @PhoenixWright I will try that tomorrow 😊

**Comment by FultonBrowne** [comment]
@PhoenixWright  gson 2 + auto ignores unknown objects, I tested it (on my deployment server) and it worked!

**Comment by PhoenixWright** [comment]
Nice! That makes things easy.
